model:
  name: "DQN"
  batch_size: 32
  gamma: 1
  initial_eps: 1.0
  final_eps: 0.1
  final_eps_step: 1000000
  capacity: 100000
  learning_starts: 50000

env:
  name: "Pong"

train:
  learning_rate: 0.00025
  steps: 10000000

test:
  n_episode: 10

load_state: False
test_mode: False